server:
  port: 22513
  servlet:
    context-path: /
dubbo:
  registry:
    address: nacos://49.232.89.51:8848?namespace=5792f7b5-a856-4457-8c62-a46b2d7fb489
  application:
    name: member-consume
spring:
  main:
    allow-bean-definition-overriding: true